marakiteferi/jobspark-joblisting-app

- resources/views/components/layout.blade.php
> added layout blade view

- resources/views/partials/_hero.blade.php
> added hero blade

- resources/views/partials/_search.blade.php
> added search blade

- resources/views/components/card.blade.php
> added card blade view

- resources/views/listings/manage.blade.php
> added manage blade

- resources/views/components/flash-message.blade.php
added flash-message  blade view
> added flash-message  blade view

- resources/views/components/listing-card.blade.php
> added listing card blade

- resources/views/components/listing-tags.blade.php
> added listing tags blade

- app/Models/Listing.php
- app/Models/User.php
creating a php file for both  listen and user
> added listening snd user php

- app/Http/Controllers/ListingController.php
- app/Http/Controllers/UserController.php
making controller for both user and listen
> making controller for both user and listen

- resources/views/vendor/pagination/bootstrap-4.blade.php
> added bootstrap styling

- resources/views/users/login.blade.php
- resources/views/users/register.blade.php
creating a user file holding both login.blade and register.blade
> creating a user file holding both login.blade and register.blade

- resources/views/vendor/pagination/default.blade.php
added default blade  bootstrap styling
> added default blade  bootstrap styling

- resources/views/vendor/pagination/simple-bootstrap-4.blade.php
added simple bootstrap  styling
> added simple bootstrap  styling

- database/migrations/2022_04_22_163902_create_listings_table.php
> added listing migration

- app/Models/Listing.php
> added listing model

- app/Http/Controllers/ListingController.php
- resources/views/listings/create.blade.php
added controller and listing create blade view
> added controller and listing create blade view

- resources/views/listings/edit.blade.php
added listing edit  Blade view
> added listing edit  Blade view

- routes/web.php
> added routing

- database/seeders/DatabaseSeeder.php
- routes/web.php
> added database seeder

- resources/views/vendor/pagination/semantic-ui.blade.php
> added semantic ui

- resources/views/vendor/pagination/simple-bootstrap-5.blade.php
> added simple ui

- resources/views/vendor/pagination/simple-tailwind.blade.php
> added tailwind styling

- resources/views/vendor/pagination/tailwind.blade.php
> added tailwind blade php
